# SITE SETTINGS
title: My Page                            # Title in top navigation bar (navbar) and <head>
author: Bram van Bunnik                   # Used for copyright statement in footer
remote_theme: peterdesmet/petridish@3.0   # Theme used

# SOCIAL PROFILES
social:
  email: bram.vanbunnik@ed.ac.uk
  twitter: bvanbunnik
  github: bvbunnik               # Can also be a github_username/repository
  mastodon: 
  facebook:                             # A URL
  disqus:                # Enable Disqus comments from disqus_sitename.disqus.com
