# SITE SETTINGS
title: My Page                            # Title in top navigation bar (navbar) and <head>
author: Bram van Bunnik                   # Used for copyright statement in footer
remote_theme: peterdesmet/petridish@3.0   # Theme used

# SOCIAL PROFILES
social:
  email: bram.vanbunnik@ed.ac.uk
  twitter: bvanbunnik
  github: bvbunnik               # Can also be a github_username/repository
  mastodon: 
  facebook:                             # A URL
  disqus:                # Enable Disqus comments from disqus_sitename.disqus.com

# THEME SETTINGS (ALL OPTIONAL)
posts_on_home: 3                        # Show x number of latest posts on homepage, can be 0
tweets_on_home: true                    # Show Twitter feed of social.twitter on homepage
archive_permalink: /blog/               # Permalink of page using the archive.html layout, required when using post tags
github_edit: true                       # Show an "edit this page" link in the footer, can also be name of branch (default: main)
colors:
  links: "#007bff"                      # Color for links: use a readable color that contrasts well with dark text
  banner: "#007bff"                     # Background color for page banners: use color that contrasts well with white
  footer: "#6c757d"                     # Background color for footer: use color that contrasts well with white
font_serif: true                        # Font type for page content: serif (default) or slightly smaller sans-serif
rounded_corners: true                   # Enable (default) rounded corners on boxes and buttons
logo: /assets/theme/images/petri-dish_1f9eb.png # Logo in navbar, will be displayed with 30px height
